export const skipTests: string[] = [
  'browser-rendering/session-management.spec.ts > should close session after keep_alive',
  'browser-rendering/session-management.spec.ts > should keep session open when closing browser created with connect',
  'browser-rendering/session-management.spec.ts > should show sessionId in active sessions under limits endpoint',
  'library/browsercontext-add-cookies.spec.tsView Trace > should set cookie with reasonable defaults',
  'library/browsercontext-basic.spec.ts > should make a copy of default viewport',
  'library/browsercontext-cookies-third-party.spec.tsView Trace > should(not) block third party cookies - ephemeral context',
  'library/browsercontext-cookies.spec.tsView Trace > should get a non-session cookie',
  'library/browsercontext-events.spec.tsView Trace > console event should work in immediately closed popup',
  'library/browsercontext-events.spec.tsView Trace > console event should work in popup 2',
  'library/browsercontext-events.spec.tsView Trace > dialog event should work in immediately closed popup',
  'library/browsercontext-events.spec.tsView Trace > dialog event should work in popup 2',
  'library/browsercontext-events.spec.tsView Trace > dialog event should work in popup',
  'library/browsercontext-har.spec.tsView Trace > should goBack to redirected navigation',
  'library/browsercontext-locale.spec.ts > should affect navigator.language in popups',
  'library/browsercontext-service-worker-policy.spec.tsView Trace > block > blocks service worker registration',
  'library/browsercontext-storage-state.spec.ts > should handle missing file',
  'library/browsercontext-storage-state.spec.ts > should round-trip through the file',
  'library/browsercontext-strict.spec.tsView Trace > strict context mode > should fail page.click in strict mode',
  'library/browsercontext-strict.spec.tsView Trace > strict context mode > should fail page.textContent in strict mode',
  'library/browsercontext-viewport-mobile.spec.ts > mobile viewport > should emulate the hover media feature',
  'library/browsercontext-viewport-mobile.spec.ts > mobile viewport > view scale should reset after navigation',
  'library/browsercontext-viewport.spec.ts > should set window.screen.orientation.type for mobile devices',
  'library/capabilities.spec.tsView Trace > should not auto play audio',
  'library/capabilities.spec.tsView Trace > should not crash on feature detection for PublicKeyCredential',
  'library/download.spec.ts > should be able to download a inline PDF file via response interception',
  'library/download.spec.ts > should be able to download a PDF file',
  'library/har.spec.ts > should attach content',
  'library/har.spec.ts > should have version and creator',
  'library/har.spec.ts > should include API request',
  'library/har.spec.ts > should include content @smoke',
  'library/har.spec.ts > should include cookies',
  'library/har.spec.ts > should include sizes',
  'library/har.spec.ts > should report the correct response body size when the bodySize is 0',
  'library/ignorehttpserrors.spec.ts > should isolate contexts',
  'library/ignorehttpserrors.spec.ts > should isolated contexts that share network process',
  'library/page-event-crash.spec.ts > should emit crash event when page crashes',
  'library/page-event-crash.spec.tsView Trace > should be able to close context when page crashes',
  'library/page-event-crash.spec.tsView Trace > should cancel waitForEvent when page crashes',
  'library/page-event-crash.spec.tsView Trace > should throw on any action after page crashes',
  'library/permissions.spec.ts > permissions > should isolate permissions between browser contexts',
  'library/permissions.spec.tsView Trace > local network request is allowed from public origin',
  'library/permissions.spec.tsView Trace > permissions > should be prompt by default',
  'library/permissions.spec.tsView Trace > permissions > should prompt for geolocation permission when origin is not listed',
  'library/permissions.spec.tsView Trace > permissions > should reset permissions',
  'library/permissions.spec.tsView Trace > permissions > should trigger permission onchange',
  'library/popup.spec.ts > BrowserContext.addInitScript should apply to an in-process popup',
  'library/popup.spec.ts > should expose function from browser context',
  'library/popup.spec.ts > should inherit touch support from browser context',
  'library/popup.spec.ts > should inherit viewport size from browser context',
  'library/popup.spec.ts > should not dispatch binding on a closed page',
  'library/popup.spec.ts > should respect routes from browser context when using window.open',
  'library/route-web-socket.spec.ts > no-match > should pass through the required protocol',
  'library/route-web-socket.spec.ts > pass-through > should pass through the required protocol',
  'library/route-web-socket.spec.tsView Trace > no-mock > should pass through the required protocol',
  'library/screenshot.spec.ts > element screenshot > should restore default viewport after fullPage screenshot',
  'library/shared-worker.spec.ts > should survive shared worker restart',
  'library/tracing.spec.tsView Trace > should include context API requests',
  'page/elementhandle-screenshot.spec.tsView Trace > element screenshot > should capture full element when larger than viewport',
  'page/expect-boolean.spec.tsView Trace > toBeChecked > fail missing',
  'page/expect-boolean.spec.tsView Trace > toBeChecked > fail with checked:false',
  'page/expect-boolean.spec.tsView Trace > toBeChecked > fail with indeterminate: true',
  'page/expect-boolean.spec.tsView Trace > toBeChecked > fail with not',
  'page/expect-boolean.spec.tsView Trace > toBeChecked > fail',
  'page/expect-boolean.spec.tsView Trace > toBeHidden > fail with not when nothing matching',
  'page/expect-misc.spec.tsView Trace > toBeInViewport > should have good stack',
  'page/expect-misc.spec.tsView Trace > toContainClass > fail with array',
  'page/expect-misc.spec.tsView Trace > toContainClass > fail',
  'page/expect-misc.spec.tsView Trace > toHaveAttribute > should match boolean attribute',
  'page/expect-misc.spec.tsView Trace > toHaveAttribute > should not match missing attribute',
  'page/expect-misc.spec.tsView Trace > toHaveClass > fail with array',
  'page/expect-misc.spec.tsView Trace > toHaveClass > fail',
  'page/expect-misc.spec.tsView Trace > toHaveCount > fail zero 2',
  'page/expect-misc.spec.tsView Trace > toHaveCount > fail zero',
  'page/expect-misc.spec.tsView Trace > toHaveJSProperty > fail boolean 2',
  'page/expect-misc.spec.tsView Trace > toHaveJSProperty > fail boolean',
  'page/expect-misc.spec.tsView Trace > toHaveJSProperty > fail number',
  'page/expect-misc.spec.tsView Trace > toHaveJSProperty > fail string',
  'page/expect-misc.spec.tsView Trace > toHaveURL > fail with negative predicate',
  'page/expect-misc.spec.tsView Trace > toHaveURL > fail with positive predicate',
  'page/expect-to-have-text.spec.tsView Trace > toHaveText with array > fail on not+empty',
  'page/expect-to-have-text.spec.tsView Trace > toHaveText with array > fail',
  'page/interception.spec.ts > should intercept by glob',
  'page/interception.spec.tsView Trace > should intercept network activity from worker 2',
  'page/locator-misc-1.spec.tsView Trace > should upload the file',
  'page/page-autowaiting-no-hang.spec.tsView Trace > assigning location to about:blank',
  'page/page-basic.spec.tsView Trace > should have sane user agent',
  'page/page-evaluate.spec.tsView Trace > should respect use strict expression',
  'page/page-evaluate.spec.tsView Trace > should work with function shorthands',
  'page/page-event-popup.spec.tsView Trace > should be able to capture alert',
  'page/page-goto.spec.tsView Trace > should fail when main resources failed to load',
  'page/page-goto.spec.tsView Trace > should fail when navigating to bad SSL',
  'page/page-network-response.spec.tsView Trace > should return body for prefetch script',
  'page/page-network-sizes.spec.tsView Trace > should have the correct responseBodySize',
  'page/page-network-sizes.spec.tsView Trace > should set bodySize to 0 when there was no response body',
  'page/page-request-intercept.spec.tsView Trace > should fulfill intercepted response using alias',
  'page/page-request-intercept.spec.tsView Trace > should give access to the intercepted response',
  'page/page-screenshot.spec.tsView Trace > page screenshot animations > should wait for fonts to load',
  'page/page-set-input-files.spec.tsView Trace > should throw an error if the file does not exist',
  'page/page-set-input-files.spec.tsView Trace > should upload a file after popup',
  'page/page-set-input-files.spec.tsView Trace > should upload a folder',
  'page/page-set-input-files.spec.tsView Trace > should upload the file with spaces in name',
  'page/page-set-input-files.spec.tsView Trace > should upload the file',
  'page/page-wait-for-navigation.spec.tsView Trace > should work with clicking on links which do not commit navigation',
  'page/page-wait-for-response.spec.tsView Trace > should work with re-rendered cached IMG elements',
  'page/page-wait-for-selector-2.spec.ts > should have correct stack trace for timeout',
  'page/selectors-get-by.spec.tsView Trace > getByTestId should escape id',
  'page/selectors-get-by.spec.tsView Trace > getByTestId should work for regex',
  'page/wheel.spec.ts > should dispatch wheel events @smoke',
  'page/wheel.spec.ts > should dispatch wheel events after popup was opened @smoke',
  'page/workers.spec.ts > Page.workers @smoke',
  'page/workers.spec.tsView Trace > should emit created and destroyed events',
  'page/workers.spec.tsView Trace > should report worker script as network request',
];

export const skipErrorMessages: Array<string | RegExp> = [
  'Cloudflare Workers does not support',
  '__filename is not defined',
  '__dirname is not defined',
  `\\(\\) => {}`, // Cloudflare serializes empty arrow function with new lines
  'createHttp2Server is not defined',
  /\[unenv\] .* is not implemented yet!/,
  /Received string:\s+"Cloudflare-Workers"/,
  '.rendering.cfdata.org',
  /expect\w+ is not a function/,
  'Error: Agent not implemented',
];
