export const skipTests: string[] = [
    "oopif.spec.ts > OOPIF > should treat OOP iframes and normal iframes the same",
    "oopif.spec.ts > OOPIF > should track navigations within OOP iframes",
    "oopif.spec.ts > OOPIF > should support OOP iframes becoming normal iframes again",
    "oopif.spec.ts > OOPIF > should support frames within OOP frames",
    "oopif.spec.ts > OOPIF > should recover cross-origin frames on reconnect",
    "oopif.spec.ts > OOPIF > should support OOP iframes getting detached",
    "oopif.spec.ts > OOPIF > should support wait for navigation for transitions from local to OOPIF",
    "oopif.spec.ts > OOPIF > should keep track of a frames OOP state",
    "oopif.spec.ts > OOPIF > should support evaluating in oop iframes",
    "oopif.spec.ts > OOPIF > should provide access to elements",
    "oopif.spec.ts > OOPIF > should report oopif frames",
    "oopif.spec.ts > OOPIF > should wait for inner OOPIFs",
    "oopif.spec.ts > OOPIF > should load oopif iframes with subresources and request interception",
    "oopif.spec.ts > OOPIF > should support frames within OOP iframes",
    "oopif.spec.ts > OOPIF > clickablePoint, boundingBox, boxModel should work for elements inside OOPIFs",
    "oopif.spec.ts > OOPIF > should detect existing OOPIFs when Puppeteer connects to an existing page",
    "oopif.spec.ts > OOPIF > should support lazy OOP frames",
    "oopif.spec.ts > OOPIF > should exposeFunction on a page with a PDF viewer",
    "oopif.spec.ts > OOPIF > should evaluate on a page with a PDF viewer",
    "oopif.spec.ts > OOPIF > should support evaluateOnNewDocument",
    "oopif.spec.ts > OOPIF > should support removing evaluateOnNewDocument scripts",
    "oopif.spec.ts > OOPIF > should support exposeFunction",
    "oopif.spec.ts > OOPIF > should support removing exposed function",
    "oopif.spec.ts > OOPIF > waitForFrame > should resolve immediately if the frame already exists",
    "oopif.spec.ts > OOPIF > should report google.com frame",
    "oopif.spec.ts > OOPIF > should expose events within OOPIFs",
    "page.spec.ts > Page > Page.close > should not be visible in browser.pages",
    "page.spec.ts > Page > Page.close > should run beforeunload if asked for",
    "page.spec.ts > Page > Page.close > should terminate network waiters",
    "page.spec.ts > Page > removing and adding event handlers > should correctly fire event handlers as they are added and then removed",
    "page.spec.ts > Page > removing and adding event handlers > should correctly added and removed request events",
    "page.spec.ts > Page > Page.Events.error > should throw when page crashes",
    "page.spec.ts > Page > Page.Events.Console > should not fail for window object",
    "page.spec.ts > Page > Page.Events.Console > should return remote objects",
    "page.spec.ts > Page > Page.Events.Console > should trigger correct Log",
    "page.spec.ts > Page > Page.Events.Console > should have location when fetch fails",
    "page.spec.ts > Page > Page.exposeFunction > should throw exception in page context",
    "page.spec.ts > Page > Page.setUserAgent > should work",
    "page.spec.ts > Page > Page.setUserAgent > should work for subframes",
    "page.spec.ts > Page > Page.setUserAgent > should emulate device user-agent",
    "page.spec.ts > Page > Page.addScriptTag > should work with a path and type=module",
    "page.spec.ts > Page > Page.addScriptTag > should work with a path",
    "page.spec.ts > Page > Page.addScriptTag > should include sourcemap when path is provided",
    "page.spec.ts > Page > Page.addScriptTag > should throw when added with content to the CSP page",
    "page.spec.ts > Page > Page.addStyleTag > should work with a path",
    "page.spec.ts > Page > Page.addStyleTag > should include sourcemap when path is provided",
    "page.spec.ts > Page > Page.browser > should return the correct browser instance",
    "page.spec.ts > Page > Page.client > should return the client instance",
    "elementhandle.spec.ts > ElementHandle specs > ElementHandle.click > should not work for TextNodes",
    "elementhandle.spec.ts > ElementHandle specs > ElementHandle.click > should throw for detached nodes",
    "elementhandle.spec.ts > ElementHandle specs > ElementHandle.click > should throw for hidden nodes",
    "elementhandle.spec.ts > ElementHandle specs > ElementHandle.click > should throw for recursively hidden nodes",
    "elementhandle.spec.ts > ElementHandle specs > ElementHandle.click > should throw for <br> elements",
    "elementhandle.spec.ts > ElementHandle specs > Custom queries > should register and unregister",
    "elementhandle.spec.ts > ElementHandle specs > Custom queries > should work for multiple elements",
    "elementhandle.spec.ts > ElementHandle specs > Custom queries > should eval correctly",
    "elementhandle.spec.ts > ElementHandle specs > Custom queries > should wait correctly with waitForSelector",
    "elementhandle.spec.ts > ElementHandle specs > Custom queries > should wait correctly with waitForSelector on an element",
    "elementhandle.spec.ts > ElementHandle specs > Custom queries > should wait correctly with waitFor",
    "elementhandle.spec.ts > ElementHandle specs > Custom queries > should work when both queryOne and queryAll are registered",
    "elementhandle.spec.ts > ElementHandle specs > Custom queries > should eval when both queryOne and queryAll are registered",
    "elementhandle.spec.ts > ElementHandle specs > ElementHandle[Symbol.dispose] > should work",
    "elementhandle.spec.ts > ElementHandle specs > ElementHandle[Symbol.asyncDispose] > should work",
    "elementhandle.spec.ts > ElementHandle specs > ElementHandle.move > should work",
    "queryhandler.spec.ts > Query handler tests > Text selectors > in Page > should query existing element",
    "queryhandler.spec.ts > Query handler tests > Text selectors > in Page > should return empty array for non-existing element",
    "queryhandler.spec.ts > Query handler tests > Text selectors > in Page > should return first element",
    "queryhandler.spec.ts > Query handler tests > Text selectors > in Page > should pierce shadow DOM",
    "queryhandler.spec.ts > Query handler tests > Text selectors > in Page > should query deeply nested text",
    "queryhandler.spec.ts > Query handler tests > Text selectors > in Page > should query inputs",
    "queryhandler.spec.ts > Query handler tests > Text selectors > in Page > should not query radio",
    "queryhandler.spec.ts > Query handler tests > Text selectors > in Page > should query text spanning multiple elements",
    "queryhandler.spec.ts > Query handler tests > Text selectors > in Page > should clear caches",
    "queryhandler.spec.ts > Query handler tests > Text selectors > in ElementHandles > should query existing element",
    "queryhandler.spec.ts > Query handler tests > Text selectors > in ElementHandles > should return null for non-existing element",
    "cookies.spec.ts > Cookie specs > Page.cookies > should return no cookies in pristine browser context",
    "cookies.spec.ts > Cookie specs > Page.cookies > should get a cookie",
    "cookies.spec.ts > Cookie specs > Page.cookies > should get multiple cookies",
    "cookies.spec.ts > Cookie specs > Page.setCookie > should isolate cookies in browser contexts",
    "cookies.spec.ts > Cookie specs > Page.setCookie > should set cookie with reasonable defaults",
    "cookies.spec.ts > Cookie specs > Page.setCookie > should set a cookie with a path",
    "cookies.spec.ts > Cookie specs > Page.setCookie > should set a cookie on a different domain",
    "cookies.spec.ts > Cookie specs > Page.setCookie > should set cookies from a frame",
    "cookies.spec.ts > Cookie specs > Page.deleteCookie > should not delete cookie for different domain",
    "cookies.spec.ts > Cookie specs > Page.deleteCookie > should delete cookie for specified URL",
    "locator.spec.ts > Locator > Locator.click > should time out",
    "locator.spec.ts > Locator > Locator.click > should retry clicks on errors",
    "locator.spec.ts > Locator > Locator.click > can be aborted",
    "locator.spec.ts > Locator > Locator.race > races multiple locators",
    "locator.spec.ts > Locator > Locator.race > can be aborted",
    "locator.spec.ts > Locator > Locator.race > should time out when all locators do not match",
    "locator.spec.ts > Locator > Locator.race > should not time out when one of the locators matches",
    "locator.spec.ts > Locator > Locator.prototype.filter > should resolve as soon as the predicate matches",
    "navigation.spec.ts > navigation > Page.goto > should fail when navigating to bad url",
    "navigation.spec.ts > navigation > Page.goto > should fail when navigating to bad SSL",
    "navigation.spec.ts > navigation > Page.goto > should fail when main resources failed to load",
    "navigation.spec.ts > navigation > Page.goto > should not leak listeners during navigation",
    "navigation.spec.ts > navigation > Page.goto > should not leak listeners during bad navigation",
    "navigation.spec.ts > navigation > Page.goto > should not leak listeners during navigation of 11 pages",
    "navigation.spec.ts > navigation > Page.goto > should fail when navigating and show the url at the error message",
    "navigation.spec.ts > navigation > Page.goBack > should work",
    "queryselector.spec.ts > querySelector > Page.$$eval > should handle many elements",
    "queryselector.spec.ts > querySelector > QueryAll > should have registered handler",
    "queryselector.spec.ts > querySelector > QueryAll > $$ should query existing elements",
    "queryselector.spec.ts > querySelector > QueryAll > $$ should return empty array for non-existing elements",
    "queryselector.spec.ts > querySelector > QueryAll > $$eval should work",
    "queryselector.spec.ts > querySelector > QueryAll > $$eval should accept extra arguments",
    "queryselector.spec.ts > querySelector > QueryAll > $$eval should accept ElementHandles as arguments",
    "queryselector.spec.ts > querySelector > QueryAll > $$eval should handle many elements",
    "coverage.spec.ts > Coverage specs > JSCoverage > should report sourceURLs",
    "coverage.spec.ts > Coverage specs > JSCoverage > should ignore eval() scripts by default",
    "coverage.spec.ts > Coverage specs > JSCoverage > should not ignore eval() scripts if reportAnonymousScripts is true",
    "coverage.spec.ts > Coverage specs > JSCoverage > should work with conditionals",
    "coverage.spec.ts > Coverage specs > JSCoverage > resetOnNavigation > should report scripts across navigations when disabled",
    "coverage.spec.ts > Coverage specs > CSSCoverage > should work with complicated usecases",
    "evaluation.spec.ts > Evaluation specs > Page.evaluate > should replace symbols with undefined",
    "evaluation.spec.ts > Evaluation specs > Page.evaluate > should work for circular object",
    "evaluation.spec.ts > Evaluation specs > Page.evaluate > should throw if elementHandles are from other frames",
    "evaluation.spec.ts > Evaluation specs > Page.evaluate > should transfer 100Mb of data from page to node.js",
    "evaluation.spec.ts > Evaluation specs > Page.evaluate > should return properly serialize objects with unknown type fields",
    "evaluation.spec.ts > Evaluation specs > Frame.evaluate > should execute after cross-site navigation",
    "jshandle.spec.ts > JSHandle > JSHandle.toString > should work for complicated objects",
    "jshandle.spec.ts > JSHandle > JSHandle.toString > should work with window subtypes",
    "jshandle.spec.ts > JSHandle > JSHandle[Symbol.dispose] > should work",
    "jshandle.spec.ts > JSHandle > JSHandle[Symbol.asyncDispose] > should work",
    "jshandle.spec.ts > JSHandle > JSHandle.move > should work",
    "click.spec.ts > Page.click > should click the button if window.Node is removed",
    "click.spec.ts > Page.click > should click on a span with an inline element inside",
    "click.spec.ts > Page.click > should not throw UnhandledPromiseRejection when page closes",
    "click.spec.ts > Page.click > should click the button with fixed position inside an iframe",
    "browser-rendering/session-management.spec.ts > should keep session open when closing browser created with connect",
    "browser-rendering/session-management.spec.ts > should close session after keep_alive",
    "browser-rendering/session-management.spec.ts > should show sessionId in active sessions under limits endpoint",
    "browser-rendering/smoke.spec.ts > should fetch HTML content @smoke",
    "browser-rendering/smoke.spec.ts > should generate PDF @smoke",
    "dialog.spec.ts > Page.Events.Dialog > should fire",
    "dialog.spec.ts > Page.Events.Dialog > should allow accepting prompts",
    "frame.spec.ts > Frame specs > Frame Management > should handle nested frames",
    "frame.spec.ts > Frame specs > Frame.client > should return the client instance",
    "input.spec.ts > input tests > ElementHandle.uploadFile > should read the file",
    "input.spec.ts > input tests > FileChooser.accept > should be able to read selected file",
    "mouse.spec.ts > Mouse > should not throw if buttons are pressed twice",
    "mouse.spec.ts > Mouse > should reset properly",
    "drag-and-drop.spec.ts > Drag n\\' Drop > should drag and drop",
    "injected.spec.ts > PuppeteerUtil tests > createFunction tests > should work",
    "keyboard.spec.ts > Keyboard > should send a character with sendCharacter in iframe"
];
