name: Puppeteer Canary CI

# Declare default permissions as read only.
permissions: read-all

on:
  schedule:
    # Run everyday at: https://crontab.guru/#0_8_*_*_*.
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  canary-chrome-tests:
    name: ${{ matrix.suite }} tests on ${{ matrix.os }} (${{ matrix.shard }}) ${{ matrix.configs }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        suite:
          - chrome-headless
          - chrome-headful
          - chrome-headless-shell
        os:
          - ubuntu-latest
          - windows-latest
          - macos-13
        shard:
          - 1-2
          - 2-2
        configs:
          - experimental
          - stable
        exclude:
          - os: macos-13
            suite: chrome-headful
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          cache: npm
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@eea3c9f0385a39e6eb4ff6a6daa273311381d436 # setup-github-actions-caching/v2.0.2
      - name: Build packages
        run: npm run build --workspace @puppeteer-test/test
      - name: Install Chrome Canary
        id: browser
        run: node tools/download_chrome_canary.mjs $HOME/.cache/puppeteer/chrome-canary
      - name: Apply Canary expectations
        run: node tools/merge-canary-test-expectations.mjs
      - name: Run all tests (for non-Linux)
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: npm run test -- --shard '${{ matrix.shard }}' --test-suite ${{ matrix.suite }} --save-stats-to /tmp/artifacts/${{ github.event_name }}_INSERTID.json
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.browser.outputs.executablePath }}
          PUPPETEER_TEST_EXPERIMENTAL_CHROME_FEATURES: ${{ matrix.configs == 'experimental' }}
      - name: Run all tests (for Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: xvfb-run --auto-servernum npm run test -- --shard '${{ matrix.shard }}' --test-suite ${{ matrix.suite }} --save-stats-to /tmp/artifacts/${{ github.event_name }}_INSERTID.json
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.browser.outputs.executablePath }}
          PUPPETEER_TEST_EXPERIMENTAL_CHROME_FEATURES: ${{ matrix.configs == 'experimental' }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.suite }}-${{ matrix.shard }}-${{ matrix.configs }}
          path: /tmp/artifacts/*.json

  report-results:
    name: 'Report results'
    needs: [canary-chrome-tests]
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: ${{ always() }}
    steps:
      - name: Post comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        if: ${{ needs.canary-chrome-tests.result != 'success'}}
        with:
          # https://github.com/puppeteer/puppeteer/issues/12379
          issue-number: 12379
          body: |
            ❌ Tests with Chrome Canary failed

            ---
            [Link](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
      - name: Post comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        if: ${{ needs.canary-chrome-tests.result == 'success'}}
        with:
          # https://github.com/puppeteer/puppeteer/issues/12379
          issue-number: 12379
          body: |
            ✅ Tests with Chrome Canary succeeded

            ---
            [Link](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
