name: "Puppeteer for Cloudflare - PR Package Preview"
permissions:
  contents: read

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/cf_puppeteer_*.yml'
      - '.npmrc'
      - 'package.json'
      - 'packages/browser-test-runtime/**'
      - 'packages/puppeteer-cloudflare/**'
      - 'patches/playwright.patch'
      - 'patches/puppeteer.patch'
      - 'scripts/**'
      - 'submodules/playwright'
      - 'submodules/jest'
      - 'submodules/puppeteer'
  workflow_dispatch:

concurrency:
  group: cf-puppeteer-preview-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Validate and Publish Package Preview
        run: |
          npm ci
          git submodule update --init
          npm run check:patches
          npm run build:puppeteer
          npm run test:bundle:prebuilt --workspace @cloudflare/puppeteer
          npm --prefix packages/puppeteer-cloudflare/tests run test-types
          npm run check:submodules
          npm exec -- pkg-pr-new publish packages/puppeteer-cloudflare
