name: "Playwright for Cloudflare - Pre-Release"
permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Generate Pre-Release
        run: |
          npm ci
          git submodule update --init
          npm run check:patches
          npm run build --workspace @cloudflare/playwright
          npm run check:submodules
          cd packages/playwright-cloudflare
          npx pkg-pr-new publish
