name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          # Issue settings
          stale-issue-message: >
            We're marking this issue as unconfirmed because it has not had recent activity and 
            we weren't able to confirm it yet. It will be closed if no further activity occurs
            within the next 30 days.
          close-issue-message: >
            We are closing this issue. If the issue still persists in the latest version of
            Puppeteer, please reopen the issue and update the description. We will try our
            best to accommodate it!
          stale-issue-label: 'unconfirmed'
          exempt-issue-labels: 'confirmed,feature'
          # PR settings
          days-before-pr-close: -1
